baseurl = "https://fatoshalimi.com"
metaDataFormat = "yaml"
title = "Fatos Halimi"
theme = ["hugo-cloak-email","blist"]

DefaultContentLanguage = "de"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "EN"
    [languages.en.params]
      description = "Product Owner and Software Engineer sharing insights on technology and agile development."
      introPhoto = "/memoji.png"
      logo = "/favicon.png"
      impressum = "/en/page/imprint"

    [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 2

    [[languages.en.menu.main]]
        name = "About Me"
        url = "page/about/"
        weight = 3

    #[[languages.en.menu.main]]
    #    name = "Tags"
    #    url = "tags"
    #    weight = 3

    #[[languages.en.menu.main]]
    #    name = "Top Post"
    #    url = "/en/blog/emoji-support/"
    #    weight = 4

  [languages.de]
    contentDir = "content/de" # Deutsch
    weight = 2
    languageName = "DE"
    title = "Fatos Halimi"
    [languages.de.params]
      description = "Product Owner und Software Engineer mit Fokus auf Technologie und agiles Projektmanagement."
      introPhoto = "/memoji.png"
      logo = "/favicon.png"
      impressum = "/de/page/impressum"

    [[languages.de.menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[languages.de.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 2

    [[languages.de.menu.main]]
        name = "Über mich"
        url = "page/about/"
        weight = 3

    #[[languages.de.menu.main]]
    #    name = "Tags"
    #    url = "tags"
    #    weight = 3

[params]
  description = "Personal homepage of Fatos Halimi."
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © {year} - Fatos Halimi · All rights reserved"
  favicon = "/favicon.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-gray-50"

  # The page bundle that is shown on the front page
  #frontBundle = "blog"
  frontBundle = "page/about/"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = ""

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = ""
  description = ""

  #[[params.homepage.social.icons]]
  #  website = "twitter"
  #  url = "https://twitter.com/"
  [[params.homepage.social.icons]]
    website = "mail"
    url = "https://www.linkedin.com/in/fatos-halimi/"
  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://www.linkedin.com/in/fatos-halimi/"
  #[[params.homepage.social.icons]]
  #  website = "xing"
  #  url = "https://www.xing.com/profile/"
  #[[params.homepage.social.icons]]
  #  website = "telegram"
  #  url = "https://t.me/"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/fatoshalimi"
  #[[params.homepage.social.icons]]
  #  website = "buymeacoffee"
  #  url = "https://www.buymeacoffee.com/"
  #[[params.homepage.social.icons]]
  #  website = "medium"
  #  url = "https://medium.com/"
  #[[params.homepage.social.icons]]
  #  website = "reddit"
  #  url = "https://reddit.com/"
  #[[params.homepage.social.icons]]
  #  website = "dribbble"
  #  url = "https://dribbble.com/"
  #[[params.homepage.social.icons]]
  #  website = "stackoverflow"
  #  url = "https://stackoverflow.com/"
  #[[params.homepage.social.icons]]
  #  website = "xda"
  #  url = "https://forum.xda-developers.com/"
  #[[params.homepage.social.icons]]
  #  website = "tiktok"
  #  url = "https://tiktok.com"
  #[[params.homepage.social.icons]]
  #  website = "googlescholar"
  #  url = "https://scholar.google.com/"
  #[[params.homepage.social.icons]]
  #  website = "mastodon"
  #  url = "https://joinmastodon.org"
  #[[params.homepage.social.icons]]
  #  website = "youtube"
  #  url = "https://youtube.com"
  #[[params.homepage.social.icons]]
  #  website = "instagram"
  #  url = "https://instagram.com"
  #[[params.homepage.social.icons]]
  #  website = "facebook"
  #  url = "https://facebook.com"
  #[[params.homepage.social.icons]]
  #  website = "behance"
  #  url = "https://behance.net"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
